version: '3.9'

services:
  go-app:
    container_name: go-storage-app
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "44044:44044"
